#!/bin/sh
#
# monitor setup
bspc monitor -d term web code music chat

#bspc rule -a Alacritty desktop=^1
#bspc rule -a code-oss desktop=^3
#bspc rule -a firefox desktop=^2

# Jalankan perintah environment dasar
export PATH="$HOME/.local/bin:$PATH"
# Set environment variables
export XDG_CURRENT_DESKTOP='bspwm'
export TERMINAL=alacritty
## Fix java applications
export _JAVA_AWT_WM_NONREPARENTING=1

run() {
  if ! pidof -q "$1"; then
    "$@" &
  fi
}


# Border
bspc config border_width                2
bspc config border_radius               25
bspc config window_gap                  5
bspc config focused_border_color        "#5E81AC"
bspc config normal_border_color         "#3B4252"
bspc config focus_follows_pointer     	true
bspc config pointer_follows_focus    	false
bspc config pointer_follows_monitor   	true
bspc config pointer_motion_interval  	7
bspc config pointer_modifier          	mod4
bspc config pointer_action1           	move
bspc config pointer_action2          	resize_side
bspc config pointer_action3           	resize_corner

# Behavior
bspc config split_ratio                 0.52
bspc config borderless_monocle          true
bspc config gapless_monocle             true
bspc config single_monocle            	true

bspc config automatic_scheme          	longest_side
bspc config initial_polarity          	second_child
bspc config removal_adjustment        	true

bspc config external_rules_command "${HOME}"/.config/bspwm/src/ExternalRules
bspc rule -a floating_rmpc state=floating rectangle=750x350+3+30
bspc rule -a ChatAi state=floating rectangle=470x665+1445+385
bspc rule -a TerminalDefault state=floating sticky=off rectangle=750x665+3+385
bspc rule -a TerminalPinned state=floating sticky=on rectangle=470x350+1445+30
bspc rule -a Terminalnvim state=floating sticky=off rectangle=1430x1020+3+30
bspc rule -a mpv state=floating sticky=off rectangle=350x350+760+385
bspc rule -a St state=floating rectangle=1120x820+3+30
bspc rule -a YaziTerm state=floating center=on rectangle=900x442+0+0
bspc rule -a Surf state=floating rectangle=470x665+1445+385



# picom
pkill picom
sleep 0.1
picom &

# Autostart background dengan slideshow 10 menit
~/.local/bin/bg-slideshow

# sxhkd
pgrep -x sxhkd > /dev/null || sxhkd &

# polybar
~/.config/polybar/launch.sh &

#eww
chmod +x ~/.config/eww/scripts/*
#eww daemon && eww open topbar

# dunst untuk widget notifikasi
pgrep -x dunst > /dev/null || dunst &

chmod +x ~/.local/bin/*
update-desktop-database ~/.local/share/applications/

