#!/bin/sh

# monitor setup
bspc monitor -d I II III IV V

# Border
bspc config border_width                4
bspc config window_gap                  5
bspc config focused_border_color        "#5E81AC"
bspc config normal_border_color         "#3B4252"

# Behavior

bspc config split_ratio                 0.52
bspc config borderless_monocle          true
bspc config gapless_monocle             true

# Autostart apps
picom --experimental-backends
xwallpaper --zoom /home/tquilla/Pictures/wallpaper/wallpaper.jpg &

# kill polybar jika sudah ada
pkill polybar | ~/.config/bspwm/polybar/launch.sh &

# sxhkd
pgrep -x sxhkd > /dev/null || sxhkd -c ~/.config/bspwm/sxhkd/sxhkdrc &

bspc wm -r
