#!/bin/sh

# monitor setup
bspc monitor -d I II III IV V

# Jalankan perintah environment dasar
export PATH="$HOME/.local/bin:$PATH"
# Set environment variables
export XDG_CURRENT_DESKTOP='bspwm'
export TERMINAL=alacritty
## Fix java applications
export _JAVA_AWT_WM_NONREPARENTING=1

run() {
  if ! pidof -q "$1"; then
    "$@" &
  fi
}


# Border
bspc config border_width                4
bspc config window_gap                  5
bspc config focused_border_color        "#5E81AC"
bspc config normal_border_color         "#3B4252"
bspc config focus_follows_pointer     	true
bspc config pointer_follows_focus    	false
bspc config pointer_follows_monitor   	true
bspc config pointer_motion_interval  	7
bspc config pointer_modifier          	mod4
bspc config pointer_action1           	move
bspc config pointer_action2          	resize_side
bspc config pointer_action3           	resize_corner

# Behavior
bspc config split_ratio                 0.52
bspc config borderless_monocle          true
bspc config gapless_monocle             true
bspc config single_monocle            	true

bspc config automatic_scheme          	longest_side
bspc config initial_polarity          	second_child
bspc config removal_adjustment        	true

bspc config external_rules_command "${HOME}"/.config/bspwm/src/ExternalRules

# Autostart apps
xwallpaper --zoom ~/Pictures/Wallpaper/wallpaper.jpg

# sxhkd
pgrep -x sxhkd > /dev/null || sxhkd &

# polybar
killall -q polybar
while pqrep -x polybar >/dev/null; do sleep 1;
done
polybar top &
polybar bottom &
polybar external &

# dunst untuk widget notifikasi
pgrep -x dunst > /dev/null || dunst &
